/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbookPjecalc2026IndexRouteImport } from './routes/ebook-pjecalc-2026/index'
import { Route as EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport } from './routes/ebook-pjecalc-2026/obrigado-analise-credito'
import { Route as EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport } from './routes/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
import { Route as EbookPjecalc2026ObrigadoRouteImport } from './routes/ebook-pjecalc-2026/obrigado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookPjecalc2026IndexRoute = EbookPjecalc2026IndexRouteImport.update({
  id: '/ebook-pjecalc-2026/',
  path: '/ebook-pjecalc-2026/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookPjecalc2026ObrigadoAnaliseCreditoRoute =
  EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado-analise-credito',
    path: '/ebook-pjecalc-2026/obrigado-analise-credito',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalc2026ObrigadoAguardandoPagamentoRoute =
  EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento',
    path: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalc2026ObrigadoRoute =
  EbookPjecalc2026ObrigadoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado',
    path: '/ebook-pjecalc-2026/obrigado',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/ebook-pjecalc-2026/': typeof EbookPjecalc2026IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/ebook-pjecalc-2026': typeof EbookPjecalc2026IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/ebook-pjecalc-2026/': typeof EbookPjecalc2026IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/ebook-pjecalc-2026/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/ebook-pjecalc-2026'
  id:
    | '__root__'
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/ebook-pjecalc-2026/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EbookPjecalc2026ObrigadoRoute: typeof EbookPjecalc2026ObrigadoRoute
  EbookPjecalc2026ObrigadoAguardandoPagamentoRoute: typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  EbookPjecalc2026ObrigadoAnaliseCreditoRoute: typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  EbookPjecalc2026IndexRoute: typeof EbookPjecalc2026IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/': {
      id: '/ebook-pjecalc-2026/'
      path: '/ebook-pjecalc-2026'
      fullPath: '/ebook-pjecalc-2026/'
      preLoaderRoute: typeof EbookPjecalc2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado-analise-credito': {
      id: '/ebook-pjecalc-2026/obrigado-analise-credito'
      path: '/ebook-pjecalc-2026/obrigado-analise-credito'
      fullPath: '/ebook-pjecalc-2026/obrigado-analise-credito'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': {
      id: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      path: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      fullPath: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado': {
      id: '/ebook-pjecalc-2026/obrigado'
      path: '/ebook-pjecalc-2026/obrigado'
      fullPath: '/ebook-pjecalc-2026/obrigado'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EbookPjecalc2026ObrigadoRoute: EbookPjecalc2026ObrigadoRoute,
  EbookPjecalc2026ObrigadoAguardandoPagamentoRoute:
    EbookPjecalc2026ObrigadoAguardandoPagamentoRoute,
  EbookPjecalc2026ObrigadoAnaliseCreditoRoute:
    EbookPjecalc2026ObrigadoAnaliseCreditoRoute,
  EbookPjecalc2026IndexRoute: EbookPjecalc2026IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
