/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuiteplusPromo0808IndexRouteImport } from './routes/suiteplus-promo-0808/index'
import { Route as PontoMagicoIndexRouteImport } from './routes/ponto-magico/index'
import { Route as ImpugnadorIndexRouteImport } from './routes/impugnador/index'
import { Route as FgtsFacilIndexRouteImport } from './routes/fgts-facil/index'
import { Route as ExtratorDeAusenciasIndexRouteImport } from './routes/extrator-de-ausencias/index'
import { Route as EbookPjecalcSuiteplusIndexRouteImport } from './routes/ebook-pjecalc-suiteplus/index'
import { Route as EbookPjecalc2026IndexRouteImport } from './routes/ebook-pjecalc-2026/index'
import { Route as ContrachequeTransparenteIndexRouteImport } from './routes/contracheque-transparente/index'
import { Route as ChatCctIndexRouteImport } from './routes/chat-cct/index'
import { Route as CalcMachineIndexRouteImport } from './routes/calc-machine/index'
import { Route as EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport } from './routes/ebook-pjecalc-2026/obrigado-analise-credito'
import { Route as EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport } from './routes/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
import { Route as EbookPjecalc2026ObrigadoRouteImport } from './routes/ebook-pjecalc-2026/obrigado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiteplusPromo0808IndexRoute = SuiteplusPromo0808IndexRouteImport.update({
  id: '/suiteplus-promo-0808/',
  path: '/suiteplus-promo-0808/',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoMagicoIndexRoute = PontoMagicoIndexRouteImport.update({
  id: '/ponto-magico/',
  path: '/ponto-magico/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpugnadorIndexRoute = ImpugnadorIndexRouteImport.update({
  id: '/impugnador/',
  path: '/impugnador/',
  getParentRoute: () => rootRouteImport,
} as any)
const FgtsFacilIndexRoute = FgtsFacilIndexRouteImport.update({
  id: '/fgts-facil/',
  path: '/fgts-facil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtratorDeAusenciasIndexRoute =
  ExtratorDeAusenciasIndexRouteImport.update({
    id: '/extrator-de-ausencias/',
    path: '/extrator-de-ausencias/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalcSuiteplusIndexRoute =
  EbookPjecalcSuiteplusIndexRouteImport.update({
    id: '/ebook-pjecalc-suiteplus/',
    path: '/ebook-pjecalc-suiteplus/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalc2026IndexRoute = EbookPjecalc2026IndexRouteImport.update({
  id: '/ebook-pjecalc-2026/',
  path: '/ebook-pjecalc-2026/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrachequeTransparenteIndexRoute =
  ContrachequeTransparenteIndexRouteImport.update({
    id: '/contracheque-transparente/',
    path: '/contracheque-transparente/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChatCctIndexRoute = ChatCctIndexRouteImport.update({
  id: '/chat-cct/',
  path: '/chat-cct/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcMachineIndexRoute = CalcMachineIndexRouteImport.update({
  id: '/calc-machine/',
  path: '/calc-machine/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookPjecalc2026ObrigadoAnaliseCreditoRoute =
  EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado-analise-credito',
    path: '/ebook-pjecalc-2026/obrigado-analise-credito',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalc2026ObrigadoAguardandoPagamentoRoute =
  EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento',
    path: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const EbookPjecalc2026ObrigadoRoute =
  EbookPjecalc2026ObrigadoRouteImport.update({
    id: '/ebook-pjecalc-2026/obrigado',
    path: '/ebook-pjecalc-2026/obrigado',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/calc-machine/': typeof CalcMachineIndexRoute
  '/chat-cct/': typeof ChatCctIndexRoute
  '/contracheque-transparente/': typeof ContrachequeTransparenteIndexRoute
  '/ebook-pjecalc-2026/': typeof EbookPjecalc2026IndexRoute
  '/ebook-pjecalc-suiteplus/': typeof EbookPjecalcSuiteplusIndexRoute
  '/extrator-de-ausencias/': typeof ExtratorDeAusenciasIndexRoute
  '/fgts-facil/': typeof FgtsFacilIndexRoute
  '/impugnador/': typeof ImpugnadorIndexRoute
  '/ponto-magico/': typeof PontoMagicoIndexRoute
  '/suiteplus-promo-0808/': typeof SuiteplusPromo0808IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/calc-machine': typeof CalcMachineIndexRoute
  '/chat-cct': typeof ChatCctIndexRoute
  '/contracheque-transparente': typeof ContrachequeTransparenteIndexRoute
  '/ebook-pjecalc-2026': typeof EbookPjecalc2026IndexRoute
  '/ebook-pjecalc-suiteplus': typeof EbookPjecalcSuiteplusIndexRoute
  '/extrator-de-ausencias': typeof ExtratorDeAusenciasIndexRoute
  '/fgts-facil': typeof FgtsFacilIndexRoute
  '/impugnador': typeof ImpugnadorIndexRoute
  '/ponto-magico': typeof PontoMagicoIndexRoute
  '/suiteplus-promo-0808': typeof SuiteplusPromo0808IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ebook-pjecalc-2026/obrigado': typeof EbookPjecalc2026ObrigadoRoute
  '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  '/ebook-pjecalc-2026/obrigado-analise-credito': typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  '/calc-machine/': typeof CalcMachineIndexRoute
  '/chat-cct/': typeof ChatCctIndexRoute
  '/contracheque-transparente/': typeof ContrachequeTransparenteIndexRoute
  '/ebook-pjecalc-2026/': typeof EbookPjecalc2026IndexRoute
  '/ebook-pjecalc-suiteplus/': typeof EbookPjecalcSuiteplusIndexRoute
  '/extrator-de-ausencias/': typeof ExtratorDeAusenciasIndexRoute
  '/fgts-facil/': typeof FgtsFacilIndexRoute
  '/impugnador/': typeof ImpugnadorIndexRoute
  '/ponto-magico/': typeof PontoMagicoIndexRoute
  '/suiteplus-promo-0808/': typeof SuiteplusPromo0808IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/calc-machine/'
    | '/chat-cct/'
    | '/contracheque-transparente/'
    | '/ebook-pjecalc-2026/'
    | '/ebook-pjecalc-suiteplus/'
    | '/extrator-de-ausencias/'
    | '/fgts-facil/'
    | '/impugnador/'
    | '/ponto-magico/'
    | '/suiteplus-promo-0808/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/calc-machine'
    | '/chat-cct'
    | '/contracheque-transparente'
    | '/ebook-pjecalc-2026'
    | '/ebook-pjecalc-suiteplus'
    | '/extrator-de-ausencias'
    | '/fgts-facil'
    | '/impugnador'
    | '/ponto-magico'
    | '/suiteplus-promo-0808'
  id:
    | '__root__'
    | '/'
    | '/ebook-pjecalc-2026/obrigado'
    | '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
    | '/ebook-pjecalc-2026/obrigado-analise-credito'
    | '/calc-machine/'
    | '/chat-cct/'
    | '/contracheque-transparente/'
    | '/ebook-pjecalc-2026/'
    | '/ebook-pjecalc-suiteplus/'
    | '/extrator-de-ausencias/'
    | '/fgts-facil/'
    | '/impugnador/'
    | '/ponto-magico/'
    | '/suiteplus-promo-0808/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EbookPjecalc2026ObrigadoRoute: typeof EbookPjecalc2026ObrigadoRoute
  EbookPjecalc2026ObrigadoAguardandoPagamentoRoute: typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRoute
  EbookPjecalc2026ObrigadoAnaliseCreditoRoute: typeof EbookPjecalc2026ObrigadoAnaliseCreditoRoute
  CalcMachineIndexRoute: typeof CalcMachineIndexRoute
  ChatCctIndexRoute: typeof ChatCctIndexRoute
  ContrachequeTransparenteIndexRoute: typeof ContrachequeTransparenteIndexRoute
  EbookPjecalc2026IndexRoute: typeof EbookPjecalc2026IndexRoute
  EbookPjecalcSuiteplusIndexRoute: typeof EbookPjecalcSuiteplusIndexRoute
  ExtratorDeAusenciasIndexRoute: typeof ExtratorDeAusenciasIndexRoute
  FgtsFacilIndexRoute: typeof FgtsFacilIndexRoute
  ImpugnadorIndexRoute: typeof ImpugnadorIndexRoute
  PontoMagicoIndexRoute: typeof PontoMagicoIndexRoute
  SuiteplusPromo0808IndexRoute: typeof SuiteplusPromo0808IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suiteplus-promo-0808/': {
      id: '/suiteplus-promo-0808/'
      path: '/suiteplus-promo-0808'
      fullPath: '/suiteplus-promo-0808/'
      preLoaderRoute: typeof SuiteplusPromo0808IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto-magico/': {
      id: '/ponto-magico/'
      path: '/ponto-magico'
      fullPath: '/ponto-magico/'
      preLoaderRoute: typeof PontoMagicoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impugnador/': {
      id: '/impugnador/'
      path: '/impugnador'
      fullPath: '/impugnador/'
      preLoaderRoute: typeof ImpugnadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fgts-facil/': {
      id: '/fgts-facil/'
      path: '/fgts-facil'
      fullPath: '/fgts-facil/'
      preLoaderRoute: typeof FgtsFacilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrator-de-ausencias/': {
      id: '/extrator-de-ausencias/'
      path: '/extrator-de-ausencias'
      fullPath: '/extrator-de-ausencias/'
      preLoaderRoute: typeof ExtratorDeAusenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-suiteplus/': {
      id: '/ebook-pjecalc-suiteplus/'
      path: '/ebook-pjecalc-suiteplus'
      fullPath: '/ebook-pjecalc-suiteplus/'
      preLoaderRoute: typeof EbookPjecalcSuiteplusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/': {
      id: '/ebook-pjecalc-2026/'
      path: '/ebook-pjecalc-2026'
      fullPath: '/ebook-pjecalc-2026/'
      preLoaderRoute: typeof EbookPjecalc2026IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracheque-transparente/': {
      id: '/contracheque-transparente/'
      path: '/contracheque-transparente'
      fullPath: '/contracheque-transparente/'
      preLoaderRoute: typeof ContrachequeTransparenteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-cct/': {
      id: '/chat-cct/'
      path: '/chat-cct'
      fullPath: '/chat-cct/'
      preLoaderRoute: typeof ChatCctIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc-machine/': {
      id: '/calc-machine/'
      path: '/calc-machine'
      fullPath: '/calc-machine/'
      preLoaderRoute: typeof CalcMachineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado-analise-credito': {
      id: '/ebook-pjecalc-2026/obrigado-analise-credito'
      path: '/ebook-pjecalc-2026/obrigado-analise-credito'
      fullPath: '/ebook-pjecalc-2026/obrigado-analise-credito'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoAnaliseCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado-aguardando-pagamento': {
      id: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      path: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      fullPath: '/ebook-pjecalc-2026/obrigado-aguardando-pagamento'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoAguardandoPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook-pjecalc-2026/obrigado': {
      id: '/ebook-pjecalc-2026/obrigado'
      path: '/ebook-pjecalc-2026/obrigado'
      fullPath: '/ebook-pjecalc-2026/obrigado'
      preLoaderRoute: typeof EbookPjecalc2026ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EbookPjecalc2026ObrigadoRoute: EbookPjecalc2026ObrigadoRoute,
  EbookPjecalc2026ObrigadoAguardandoPagamentoRoute:
    EbookPjecalc2026ObrigadoAguardandoPagamentoRoute,
  EbookPjecalc2026ObrigadoAnaliseCreditoRoute:
    EbookPjecalc2026ObrigadoAnaliseCreditoRoute,
  CalcMachineIndexRoute: CalcMachineIndexRoute,
  ChatCctIndexRoute: ChatCctIndexRoute,
  ContrachequeTransparenteIndexRoute: ContrachequeTransparenteIndexRoute,
  EbookPjecalc2026IndexRoute: EbookPjecalc2026IndexRoute,
  EbookPjecalcSuiteplusIndexRoute: EbookPjecalcSuiteplusIndexRoute,
  ExtratorDeAusenciasIndexRoute: ExtratorDeAusenciasIndexRoute,
  FgtsFacilIndexRoute: FgtsFacilIndexRoute,
  ImpugnadorIndexRoute: ImpugnadorIndexRoute,
  PontoMagicoIndexRoute: PontoMagicoIndexRoute,
  SuiteplusPromo0808IndexRoute: SuiteplusPromo0808IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
